//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.21 at 04:08:41 PM NST 
//


package com.github.xxbeanxx.noticeseditor.bindings;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.github.xxbeanxx.noticeseditor.bindings package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.github.xxbeanxx.noticeseditor.bindings
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Notices }
     * 
     */
    public Notices createNotices() {
        return new Notices();
    }

    /**
     * Create an instance of {@link Notices.Notice }
     * 
     */
    public Notices.Notice createNoticesNotice() {
        return new Notices.Notice();
    }

    /**
     * Create an instance of {@link Notices.Notice.Title }
     * 
     */
    public Notices.Notice.Title createNoticesNoticeTitle() {
        return new Notices.Notice.Title();
    }

    /**
     * Create an instance of {@link Notices.Notice.Text }
     * 
     */
    public Notices.Notice.Text createNoticesNoticeText() {
        return new Notices.Notice.Text();
    }

}
